version: "3.2"

services:
  redis:
    image: rbekker87/redis:alpine-armhf
    networks:
      - docknet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: nc -vz 127.0.0.1 6379 || exit 1
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  docknet:
    external: true
